In [1]:
# Comprender Numpy, Pandas, Matplotlib, Sickit-Learn
import numpy as np
import pandas as pd
import matplotlib 

C:\Users\Antonio\AppData\Local\Temp\ipykernel_6260\3161492830.py:3: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [2]:
data=pd.read_csv('pokemon.csv', index_col='#')
data.head()

Name Type 1  Type 2  Total  HP  Attack  Defense  Sp. Atk  \
#                                                                              
1              Bulbasaur  Grass  Poison    318  45      49       49       65   
2                Ivysaur  Grass  Poison    405  60      62       63       80   
3               Venusaur  Grass  Poison    525  80      82       83      100   
3  VenusaurMega Venusaur  Grass  Poison    625  80     100      123      122   
4             Charmander   Fire     NaN    309  39      52       43       60   

   Sp. Def  Speed  Generation  Legendary  
#                                         
1       65     45           1      False  
2       80     60           1      False  
3      100     80           1      False  
3      120     80           1      False  
4       50     65           1      False

# Trabajo con Numpy

Una lista en Python es dinamica, por lo que puede contener distintos tipos de datos, Numpy permite trabajar con datos numericos unicamente y hacer de este proceso mas rapido al consumir menos memoria, ademas de operaciones mas eficientes en comparacion al uso de librerias como array.

In [3]:
np.array([1,4,3.14,213]) # array a partir de lista de Python
np.array([range(i,i+3) for i in [2,4,6]]) # ejemplo de creacion de matriz bidimiensional
np.array([1,2,3,4], dtype="float") # especificar tipos de datos

array([1., 2., 3., 4.])

In [4]:
# generacion de arrays
np.zeros(10, dtype=int) # genera un array de tam 10 de 0
np.ones((3,5),dtype=float) # matriz de 3x5 de 1
np.full((3,5), 3.14) # matriz de 3x5 de 3.14

np.arange(0,20,2) # arreglo de 0 a 20 va de 2 en 2
np.linspace(0,1,5) # mostrar cinco numeros entre 0 y 1 en trozos iguales
np.random.random((3,3)) # 3X3 array valores random entre 0 y 1 
np.random.normal(0,1, (3,3)) # igual, con media en 0 y desviacion estandar de 1
np.random.randint(0,10, (3,3)) # matriz de int entre 0 y 10
np.eye(3) # matriz de identidad de 3x3
np.empty(3) # crear array sin inicializar, no se guarda en memoria

array([0., 0., 0.])

In [5]:
x3=np.random.randint(10, size=(3,4,5,6)) # arreglo de (size) dimensiones  
# todos los array tienen ndim(numero de dimensiones), shape(tamanno de cada diemension) y size(tamanno total del array)
print("x3 dimensiones: ", x3.ndim)
print("x3 tamanno de dimensiones: ", x3.shape)
print("x3 tamanno de array: ", x3.size)

x3 dimensiones:  4
x3 tamanno de dimensiones:  (3, 4, 5, 6)
x3 tamanno de array:  360


In [6]:
# acceso a los elementos del array es igual que en las listas
x1=np.random.randint(10, size=(5))
print(x1)
x1[0] # primer elemento
x1[-2]# penultimo elemento
# array multidimensionales se usan coordenadas [x,y,z]

# modificar el valor igualando
x1[0]=33
x1

[1 9 4 9 0]


array([33,  9,  4,  9,  0])

In [8]:
# Desplazamiento en el array
x=np.arange(10) 
x[:5]# primeros cinco elementos
x[5:]# elementors despues de los primeros 5
x[4:7]# elementos en este rango
x[::2]# elementos en ese orden de dos en dos
x[1::2]# todos los elementos de dos en dos desde 1
x[::-1]# todos los elementos del reves
x[5::-2]# todos los elementos del reves desde el indice 5

array([4, 5, 6])